// Generated by Cypress Author on 2026-06-16.

describe('MoneyKai authentication', () => {
  beforeEach(() => {
    cy.resetMoneyKaiBrowserState();
  });

  it('submitting empty login -> shows inline validation errors', () => {
    cy.visit('/login');

    cy.get('[data-testid="login-submit"]').click();

    cy.contains('Email is required').should('be.visible');
    cy.contains('Password is required').should('be.visible');
    cy.get('[data-testid="login-email"]').should('have.attr', 'aria-invalid', 'true');
    cy.get('[data-testid="login-password"]').should('have.attr', 'aria-invalid', 'true');
  });

  it('submitting invalid login details -> blocks before auth provider call', () => {
    cy.visit('/login');

    cy.get('[data-testid="login-email"]').type('not-an-email');
    cy.get('[data-testid="login-password"]').type('123');
    cy.get('[data-testid="login-submit"]').click();

    cy.contains('Enter a valid email').should('be.visible');
    cy.contains('Minimum 6 characters').should('be.visible');
    cy.location('pathname').should('eq', '/login');
  });

  it('submitting invalid signup details -> shows all required validation states', () => {
    cy.visit('/signup');

    cy.get('[data-testid="signup-submit"]').click();

    cy.contains('Name must be at least 2 characters').should('be.visible');
    cy.contains('Enter a valid email').should('be.visible');
    cy.contains('Minimum 8 characters').should('be.visible');
  });

  it('submitting mismatched signup passwords -> stays on signup with password error', () => {
    cy.visit('/signup');

    cy.get('[data-testid="signup-full-name"]').type('Money Kai');
    cy.get('[data-testid="signup-email"]').type('user@example.com');
    cy.get('[data-testid="signup-password"]').type('correct-horse');
    cy.get('[data-testid="signup-confirm-password"]').type('battery-staple');
    cy.get('[data-testid="signup-submit"]').click();

    cy.contains('Passwords do not match').should('be.visible');
    cy.location('pathname').should('eq', '/signup');
  });

  it('visiting protected app routes while signed out -> redirects to login', () => {
    cy.visit('/transactions');

    cy.location('pathname', { timeout: 10000 }).should('eq', '/login');
    cy.contains('Welcome back').should('be.visible');
  });

  it('visiting profile editing while signed out -> redirects to login', () => {
    cy.visit('/profile-edit');

    cy.location('pathname', { timeout: 10000 }).should('eq', '/login');
    cy.contains('Welcome back').should('be.visible');
  });
});
