// Generated by Cypress Author on 2026-06-16.

describe('MoneyKai live news states', () => {
  beforeEach(() => {
    cy.resetMoneyKaiBrowserState();
  });

  it('loading live news -> shows loading state before rendering an empty feed', () => {
    cy.intercept('GET', '**/v1/news*', {
      delay: 250,
      statusCode: 200,
      body: {
        items: [],
        updatedAt: '2026-06-16T00:00:00.000Z',
        category: 'all',
      },
    }).as('newsFeed');

    cy.visit('/news');

    cy.contains('Loading the live feed...').should('be.visible');
    cy.wait('@newsFeed');
    cy.contains('No finance news is available right now.').should('be.visible');
  });

  it('failing live news request -> shows retryable error state', () => {
    cy.intercept('GET', '**/v1/news*', {
      statusCode: 503,
      body: { detail: 'News provider is temporarily unavailable.' },
    }).as('newsFeedFailure');

    cy.visit('/news');
    cy.wait('@newsFeedFailure');

    cy.contains('The live feed could not load right now.').should('be.visible');
    cy.contains('News provider is temporarily unavailable.').should('be.visible');
    cy.contains('Try again').should('be.visible');
  });
});
