// Generated by Cypress Author on 2026-06-16.

describe('MoneyKai pricing and payment edges', () => {
  beforeEach(() => {
    cy.resetMoneyKaiBrowserState();
  });

  it('viewing pricing while signed out -> shows free and Stripe-hosted premium paths', () => {
    cy.visit('/pricing');

    cy.contains('Start free. Upgrade only when deeper reporting is worth it.').should('be.visible');
    cy.contains('Free').should('be.visible');
    cy.contains('Secure checkout').should('be.visible');
    cy.contains('Stripe-hosted checkout').should('be.visible');
    cy.contains('Payment details are collected by Stripe, not stored in MoneyKai client code.').should('be.visible');
    cy.contains(/card number|cvv|expiration date/i).should('not.exist');
  });

  it('choosing the free plan while signed out -> starts account creation', () => {
    cy.visit('/pricing');

    cy.get('[data-testid="pricing-start-cta"]').click();

    cy.location('pathname').should('eq', '/signup');
    cy.contains('Create account').should('be.visible');
  });

  it('choosing premium while signed out -> does not start checkout before auth', () => {
    cy.visit('/pricing');

    cy.get('[data-testid="pricing-premium-cta"]').should('contain.text', 'Sign in to upgrade').click();

    cy.location('pathname').should('eq', '/signup');
    cy.contains('Create account').should('be.visible');
  });

  it('returning from a cancelled checkout -> explains no payment method changed', () => {
    cy.visit('/pricing?checkout=cancelled');

    cy.contains('BILLING STATUS').should('be.visible');
    cy.contains('Checkout was cancelled. No payment method was changed.').should('be.visible');
    cy.contains('Free plan active').should('be.visible');
  });
});
