/** Existing semantic names mapped to the closest official Heroicons v2 glyph. */
export const HEROICON_ALIASES: Record<string, string> = {
  'calendar-range': 'calendar-days', 'credit-card-check-outline': 'credit-card', 'heart-broken': 'heart', 'heart-half-full': 'heart', 'pin-outline': 'map-pin', 'transfer-up': 'arrow-up-tray',
  account: 'user', 'account-outline': 'user', 'account-circle-outline': 'user-circle',
  'account-group': 'user-group', 'account-group-outline': 'user-group', 'account-multiple-outline': 'users',
  'account-multiple-plus-outline': 'user-plus', 'account-plus-outline': 'user-plus', 'account-search-outline': 'user-circle', 'account-heart-outline': 'heart',
  airplane: 'paper-airplane', 'alert-circle-outline': 'exclamation-circle',
  'archive-outline': 'archive-box', 'archive-arrow-down-outline': 'archive-box-arrow-down', 'archive-arrow-up-outline': 'arrow-up-tray',
  'arrow-bottom-left': 'arrow-down-left', 'arrow-bottom-left-thick': 'arrow-down-left', 'arrow-top-right': 'arrow-up-right',
  'arrow-down-circle-outline': 'arrow-down-circle', 'arrow-up-circle-outline': 'arrow-up-circle',
  'bank-outline': 'building-library', 'bank-plus': 'building-library', 'bank-transfer': 'arrows-right-left', 'briefcase-outline': 'briefcase',
  'bell-badge-outline': 'bell-alert', 'bell-outline': 'bell', 'book-open-variant': 'book-open', 'book-open-page-variant-outline': 'book-open',
  brain: 'cpu-chip', 'bug-outline': 'bug-ant', bus: 'truck', 'calculator-variant-outline': 'calculator',
  'calendar-arrow-down': 'calendar-days', 'calendar-arrow-up': 'calendar-days', 'calendar-check-outline': 'calendar-days',
  'calendar-clock': 'calendar-days', 'calendar-month-outline': 'calendar-days', 'calendar-star': 'calendar-days', 'calendar-weekend': 'calendar-days',
  'call-split': 'arrows-right-left', 'car-off': 'truck', 'cart-off': 'shopping-cart', 'cart-outline': 'shopping-cart',
  cash: 'banknotes', 'cash-clock': 'clock', 'cash-multiple': 'banknotes', 'cash-plus': 'banknotes', 'cash-refund': 'receipt-refund',
  cellphone: 'device-phone-mobile', 'cellphone-link': 'device-phone-mobile', 'cellphone-lock': 'device-phone-mobile',
  'chart-bubble': 'chart-pie', 'chart-areaspline': 'presentation-chart-line', 'chart-bar': 'chart-bar', 'chart-box-outline': 'chart-bar-square',
  'chart-donut': 'chart-pie', 'chart-line': 'presentation-chart-line', 'chart-timeline-variant': 'presentation-chart-line',
  'checkbox-marked': 'check-circle', 'checkbox-marked-outline': 'check-circle', 'checkbox-blank-outline': 'stop',
  'check-circle-outline': 'check-circle', 'check-decagram-outline': 'check-badge', 'chevrons-left': 'chevron-double-left', 'chevrons-right': 'chevron-double-right',
  'clipboard-check-outline': 'clipboard-document-check', 'clipboard-list-outline': 'clipboard-document-list',
  'clock-check-outline': 'clock', 'clock-outline': 'clock', close: 'x-mark', 'close-circle': 'x-circle', 'close-circle-outline': 'x-circle',
  'cloud-check-outline': 'cloud', 'cloud-outline': 'cloud', 'cloud-off-outline': 'cloud', 'cloud-search-outline': 'cloud', 'cloud-upload-outline': 'cloud-arrow-up',
  'coffee-off': 'cake', 'cog-outline': 'cog-6-tooth', connection: 'link', 'credit-card-outline': 'credit-card', 'crown-outline': 'trophy',
  'currency-inr': 'currency-rupee', 'currency-usd': 'currency-dollar', 'currency-eur': 'currency-euro', 'currency-jpy': 'currency-yen',
  'database-search-outline': 'circle-stack', 'delete-outline': 'trash', devices: 'computer-desktop', 'diamond-stone': 'sparkles',
  'dots-horizontal-circle-outline': 'ellipsis-horizontal-circle', download: 'arrow-down-tray', 'email-outline': 'envelope', 'email-check-outline': 'envelope',
  'eye-off-outline': 'eye-slash', 'eye-outline': 'eye', 'file-document-outline': 'document-text', 'file-document-check-outline': 'document-check',
  'file-document-edit-outline': 'pencil-square', 'file-export-outline': 'document-arrow-down', 'file-upload-outline': 'document-arrow-up', 'file-lock-outline': 'lock-closed',
  'filter-off-outline': 'funnel', 'filter-variant': 'funnel', 'gamepad-variant-outline': 'play-circle', fire: 'fire', 'food-off': 'cake', 'fridge-outline': 'shopping-bag',
  'gift-outline': 'gift', gmail: 'envelope', 'handshake-outline': 'users', hanger: 'shopping-bag', 'help-circle-outline': 'question-mark-circle',
  'home-outline': 'home', 'home-clock-outline': 'home', 'hospital-box-outline': 'heart', 'image-search-outline': 'photo', 'inbox-outline': 'inbox',
  'information-outline': 'information-circle', laptop: 'computer-desktop', leaf: 'sparkles', 'lightbulb-on-outline': 'light-bulb', 'lightbulb-outline': 'light-bulb',
  'lightning-bolt-outline': 'bolt', 'link-variant': 'link', 'lock-alert-outline': 'lock-closed', 'lock-outline': 'lock-closed', 'lock-check-outline': 'lock-closed',
  'lock-reset': 'arrow-path', logout: 'arrow-right-start-on-rectangle', magnify: 'magnifying-glass',
  'message-processing-outline': 'chat-bubble-left-ellipsis', 'message-text-outline': 'chat-bubble-left-right', 'movie-off': 'film', ninja: 'user',
  'note-text-outline': 'document-text', 'notebook-outline': 'book-open', 'pencil-outline': 'pencil', 'palette-outline': 'swatch', 'pause-circle-outline': 'pause-circle',
  'piggy-bank-outline': 'wallet', pill: 'heart', pin: 'map-pin', 'playlist-remove': 'list-bullet', 'plus-circle-outline': 'plus-circle',
  'podium-gold': 'trophy', 'pot-steam-outline': 'cake', radar: 'signal', receipt: 'document-text', 'receipt-text-outline': 'document-text', 'receipt-text-plus-outline': 'document-plus',
  refresh: 'arrow-path', sync: 'arrow-path', 'rocket-launch-outline': 'rocket-launch',
  'safe-square-outline': 'lock-closed', 'scale-balance': 'scale', 'school-outline': 'academic-cap', 'share-variant-outline': 'share',
  'shield-account-outline': 'shield-check', 'shield-check-outline': 'shield-check', 'shield-key-outline': 'shield-check', 'shield-lock-outline': 'shield-check',
  'shopping-outline': 'shopping-bag', 'silverware-fork-knife': 'cake', sort: 'adjustments-vertical',
  'sort-alphabetical-ascending': 'bars-arrow-down', 'sort-alphabetical-descending': 'bars-arrow-up',
  'sort-calendar-ascending': 'bars-arrow-up', 'sort-calendar-descending': 'bars-arrow-down', 'sort-numeric-ascending': 'bars-arrow-up', 'sort-numeric-descending': 'bars-arrow-down',
  'source-branch': 'arrows-right-left', 'source-merge': 'arrows-right-left', speedometer: 'chart-bar', 'star-circle': 'star', 'store-outline': 'building-storefront',
  'swap-horizontal': 'arrows-right-left', 'sword-cross': 'bolt', text: 'language', 'text-box-check-outline': 'document-check', 'train-car': 'truck', transfer: 'arrows-right-left',
  'trash-can-outline': 'trash', 'trending-down': 'arrow-trending-down', 'trending-up': 'arrow-trending-up', 'trophy-outline': 'trophy', 'tune-variant': 'adjustments-horizontal',
  vibrate: 'device-phone-mobile', 'view-dashboard-outline': 'squares-2x2', 'view-list-outline': 'list-bullet', walk: 'user', 'wallet-outline': 'wallet',
};
