import type { CaptureParseStatus, CaptureSignalInput } from '@/types/capture';
import type { TransactionType } from '@/types/transaction';

export interface CaptureFixture {
  id: string;
  label: string;
  input: CaptureSignalInput;
  expected: {
    amount?: number;
    merchant?: string;
    type?: TransactionType;
    paymentMethod?: string;
    status: CaptureParseStatus;
    shouldDraft: boolean;
    category?: string;
    ignoreReasonIncludes?: string;
  };
}

export const CAPTURE_FIXTURES: CaptureFixture[] = [
  {
    id: 'upi-hdfc-cafe-debit',
    label: 'HDFC UPI debit to cafe',
    input: {
      source: 'notification',
      sourceApp: 'HDFC Bank',
      title: 'HDFC Bank',
      body: 'Rs 789.50 debited from account for UPI payment to PHASE ONE CAFE. UPI Ref 412345678901.',
      receivedAt: '2026-06-09T09:00:00.000Z',
    },
    expected: {
      amount: 789.5,
      merchant: 'PHASE ONE CAFE',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'food',
    },
  },
  {
    id: 'gpay-swiggy-paid',
    label: 'Google Pay paid to Swiggy',
    input: {
      source: 'notification',
      sourceApp: 'Google Pay',
      title: 'Payment successful',
      body: 'You paid Rs. 432.10 to Swiggy via UPI. UPI transaction ID 612233445566.',
      receivedAt: '2026-06-09T09:05:00.000Z',
    },
    expected: {
      amount: 432.1,
      merchant: 'Swiggy',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'food',
    },
  },
  {
    id: 'phonepe-person-transfer',
    label: 'PhonePe transfer to person',
    input: {
      source: 'notification',
      sourceApp: 'PhonePe',
      title: 'Money sent',
      body: 'Sent INR 450 to RAHUL SHARMA using UPI. UPI Ref No 998877665544.',
      receivedAt: '2026-06-09T09:10:00.000Z',
    },
    expected: {
      amount: 450,
      merchant: 'RAHUL SHARMA',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
    },
  },
  {
    id: 'sbi-amazon-bank-debit',
    label: 'SBI account debit at Amazon Pay',
    input: {
      source: 'notification',
      sourceApp: 'SBI',
      title: 'SBI Alert',
      body: 'A/c XX4321 debited by INR 2,350.00 at AMAZON PAY on 09-Jun. Ref 1234567890.',
      receivedAt: '2026-06-09T09:15:00.000Z',
    },
    expected: {
      amount: 2350,
      merchant: 'AMAZON PAY',
      type: 'expense',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'shopping',
    },
  },
  {
    id: 'icici-credit-card-myntra',
    label: 'ICICI credit card spend',
    input: {
      source: 'notification',
      sourceApp: 'iMobile Pay',
      title: 'Credit Card Alert',
      body: 'INR 1,999.00 spent on your ICICI Credit Card XX1002 at MYNTRA DESIGNS on 09-Jun.',
      receivedAt: '2026-06-09T09:20:00.000Z',
    },
    expected: {
      amount: 1999,
      merchant: 'MYNTRA DESIGNS',
      type: 'expense',
      paymentMethod: 'card',
      status: 'draft',
      shouldDraft: true,
      category: 'shopping',
    },
  },
  {
    id: 'hdfc-debit-card-metro',
    label: 'HDFC debit card metro spend',
    input: {
      source: 'notification',
      sourceApp: 'HDFC Bank',
      title: 'Debit Card Alert',
      body: 'Your HDFC Bank Debit Card was used for Rs 300.00 at METRO RAIL BENGALURU.',
      receivedAt: '2026-06-09T09:25:00.000Z',
    },
    expected: {
      amount: 300,
      merchant: 'METRO RAIL BENGALURU',
      type: 'expense',
      paymentMethod: 'card',
      status: 'draft',
      shouldDraft: true,
      category: 'transport',
    },
  },
  {
    id: 'paytm-wallet-jio',
    label: 'Paytm wallet recharge',
    input: {
      source: 'notification',
      sourceApp: 'Paytm',
      title: 'Wallet payment successful',
      body: 'Paid Rs 199 from Paytm Wallet to Jio Recharge. Order ID 20260609.',
      receivedAt: '2026-06-09T09:30:00.000Z',
    },
    expected: {
      amount: 199,
      merchant: 'Jio Recharge',
      type: 'expense',
      paymentMethod: 'wallet',
      status: 'draft',
      shouldDraft: true,
      category: 'bills',
    },
  },
  {
    id: 'amazon-pay-wallet',
    label: 'Amazon Pay wallet purchase',
    input: {
      source: 'notification',
      sourceApp: 'Amazon Pay',
      title: 'Payment completed',
      body: 'Wallet payment of Rs.549.00 successful at Amazon Pantry.',
      receivedAt: '2026-06-09T09:35:00.000Z',
    },
    expected: {
      amount: 549,
      merchant: 'Amazon Pantry',
      type: 'expense',
      paymentMethod: 'wallet',
      status: 'draft',
      shouldDraft: true,
      category: 'shopping',
    },
  },
  {
    id: 'axis-salary-credit',
    label: 'Axis salary credit',
    input: {
      source: 'notification',
      sourceApp: 'Axis Bank',
      title: 'Credit Alert',
      body: 'INR 25,000.00 credited to A/c XX8888 from ACME PAYROLL as salary.',
      receivedAt: '2026-06-09T09:40:00.000Z',
    },
    expected: {
      amount: 25000,
      merchant: 'ACME PAYROLL',
      type: 'income',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'allowance',
    },
  },
  {
    id: 'upi-received-priya',
    label: 'UPI received from person',
    input: {
      source: 'notification',
      sourceApp: 'BHIM',
      title: 'UPI credit',
      body: 'You received Rs 1,200.00 from PRIYA NAIR via UPI. UPI Ref 876543210987.',
      receivedAt: '2026-06-09T09:45:00.000Z',
    },
    expected: {
      amount: 1200,
      merchant: 'PRIYA NAIR',
      type: 'income',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
    },
  },
  {
    id: 'zomato-refund-credit',
    label: 'Zomato refund credit',
    input: {
      source: 'notification',
      sourceApp: 'Zomato',
      title: 'Refund processed',
      body: 'Refund of Rs 349 has been credited from Zomato order Z123.',
      receivedAt: '2026-06-09T09:50:00.000Z',
    },
    expected: {
      amount: 349,
      merchant: 'Zomato',
      type: 'income',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'refund',
    },
  },
  {
    id: 'paytm-cashback-wallet',
    label: 'Paytm cashback credit',
    input: {
      source: 'notification',
      sourceApp: 'Paytm',
      title: 'Cashback received',
      body: 'Cashback of Rs 50 credited to your Paytm Wallet for merchant payment.',
      receivedAt: '2026-06-09T09:55:00.000Z',
    },
    expected: {
      amount: 50,
      merchant: 'Paytm',
      type: 'income',
      paymentMethod: 'wallet',
      status: 'draft',
      shouldDraft: true,
      category: 'refund',
    },
  },
  {
    id: 'imps-rent-transfer',
    label: 'IMPS rent transfer',
    input: {
      source: 'notification',
      sourceApp: 'Kotak Bank',
      title: 'Debit Alert',
      body: 'IMPS transfer of Rs 5,000.00 sent to LANDLORD RAJ for rent. Ref IMPS12345.',
      receivedAt: '2026-06-09T10:00:00.000Z',
    },
    expected: {
      amount: 5000,
      merchant: 'LANDLORD RAJ',
      type: 'expense',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'rent',
    },
  },
  {
    id: 'neft-client-credit',
    label: 'NEFT client credit',
    input: {
      source: 'notification',
      sourceApp: 'HDFC Bank',
      title: 'Credit Alert',
      body: 'NEFT INR 10,000.00 credited to your account from CLIENT ABC for invoice 44.',
      receivedAt: '2026-06-09T10:05:00.000Z',
    },
    expected: {
      amount: 10000,
      merchant: 'CLIENT ABC',
      type: 'income',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'freelance',
    },
  },
  {
    id: 'pos-reliance-fresh',
    label: 'POS card spend',
    input: {
      source: 'notification',
      sourceApp: 'SBI Card',
      title: 'Card transaction',
      body: 'POS transaction of Rs 875.25 on card ending 7788 at RELIANCE FRESH BANGALORE approved.',
      receivedAt: '2026-06-09T10:10:00.000Z',
    },
    expected: {
      amount: 875.25,
      merchant: 'RELIANCE FRESH BANGALORE',
      type: 'expense',
      paymentMethod: 'card',
      status: 'draft',
      shouldDraft: true,
      category: 'shopping',
    },
  },
  {
    id: 'upi-bescom-bill',
    label: 'UPI utility bill',
    input: {
      source: 'notification',
      sourceApp: 'PhonePe',
      title: 'Payment successful',
      body: 'UPI payment of Rs 1,284.00 paid to BESCOM BILL PAYMENT.',
      receivedAt: '2026-06-09T10:15:00.000Z',
    },
    expected: {
      amount: 1284,
      merchant: 'BESCOM BILL PAYMENT',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'bills',
    },
  },
  {
    id: 'sms-hdfc-upi-debit',
    label: 'SMS HDFC UPI debit to kirana',
    input: {
      source: 'sms',
      sender: 'HDFCBK',
      body: 'A/c XX1234 debited by Rs 321.00 for UPI payment to KIRANA MART. UPI Ref 555566667777.',
      receivedAt: '2026-06-09T10:16:00.000Z',
    },
    expected: {
      amount: 321,
      merchant: 'KIRANA MART',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'shopping',
    },
  },
  {
    id: 'sms-axis-upi-p2m-swiggy-instamart',
    label: 'SMS Axis UPI P2M debit to Swiggy Instamart',
    input: {
      source: 'sms',
      sender: 'AXISBK',
      body: 'INR 293.00 debited\nA/c no. XX8690\n09-06-26, 15:21:54\nUPI/P2M/652670076603/SWIGGY INSTAMART PR\nNot you? SMS BLOCKUPI Cust ID to 900000000000\nAxis Bank',
      receivedAt: '2026-06-09T09:51:54.000Z',
    },
    expected: {
      amount: 293,
      merchant: 'SWIGGY INSTAMART PR',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'food',
    },
  },
  {
    id: 'notification-axis-upi-p2m-swiggy-instamart-sanitized',
    label: 'Native notification Axis UPI P2M debit after sanitizer',
    input: {
      source: 'notification',
      sourceApp: 'Shell',
      title: 'Axis Bank',
      body: 'INR 293.00 debited A/c no. [masked] 09-06-26, 15:21:54 UPI/P2M/[number]/SWIGGY INSTAMART PR Not you? SMS BLOCKUPI Cust ID to [number] Axis Bank',
      receivedAt: '2026-06-09T20:05:19.781Z',
    },
    expected: {
      amount: 293,
      merchant: 'SWIGGY INSTAMART PR',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'food',
    },
  },
  {
    id: 'sms-axis-upi-p2m-swiggy',
    label: 'SMS Axis UPI P2M debit to Swiggy',
    input: {
      source: 'sms',
      sender: 'AXISBK',
      body: 'INR 315.00 debited\nA/c no. XX8690\n09-06-26, 12:16:19\nUPI/P2M/652604639717/Swiggy\nNot you? SMS BLOCKUPI Cust ID to 900000000000\nAxis Bank',
      receivedAt: '2026-06-09T06:46:19.000Z',
    },
    expected: {
      amount: 315,
      merchant: 'Swiggy',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'food',
    },
  },
  {
    id: 'sms-axis-upi-p2a-person',
    label: 'SMS Axis UPI P2A debit to person',
    input: {
      source: 'sms',
      sender: 'AXISBK',
      body: 'INR 242.00 debited\nA/c no. XX8690\n22-05-26, 13:35:43\nUPI/P2A/650876838283/Ruturaj Sanjay Wark\nNot you? SMS BLOCKUPI Cust ID to 900000000000\nAxis Bank',
      receivedAt: '2026-05-22T08:05:43.000Z',
    },
    expected: {
      amount: 242,
      merchant: 'Ruturaj Sanjay Wark',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
    },
  },
  {
    id: 'sms-axis-bank-credit',
    label: 'SMS bank salary credit',
    input: {
      source: 'sms',
      sender: 'AXISBK',
      body: 'INR 15,000.00 credited to A/c XX2222 from ACME PAYROLL as salary. UTR 333344445555.',
      receivedAt: '2026-06-09T10:17:00.000Z',
    },
    expected: {
      amount: 15000,
      merchant: 'ACME PAYROLL',
      type: 'income',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'allowance',
    },
  },
  {
    id: 'sms-icici-card-spend',
    label: 'SMS credit card spend',
    input: {
      source: 'sms',
      sender: 'ICICIB',
      body: 'INR 1,250.00 spent on ICICI Credit Card XX1002 at BOOKMYSHOW on 09-Jun.',
      receivedAt: '2026-06-09T10:18:00.000Z',
    },
    expected: {
      amount: 1250,
      merchant: 'BOOKMYSHOW',
      type: 'expense',
      paymentMethod: 'card',
      status: 'draft',
      shouldDraft: true,
      category: 'entertainment',
    },
  },
  {
    id: 'sms-paytm-wallet-spend',
    label: 'SMS wallet recharge spend',
    input: {
      source: 'sms',
      sender: 'PAYTMB',
      body: 'Paid Rs 199 from Paytm Wallet to Jio Recharge. Order ID 20260609.',
      receivedAt: '2026-06-09T10:19:00.000Z',
    },
    expected: {
      amount: 199,
      merchant: 'Jio Recharge',
      type: 'expense',
      paymentMethod: 'wallet',
      status: 'draft',
      shouldDraft: true,
      category: 'bills',
    },
  },
  {
    id: 'sms-zomato-refund',
    label: 'SMS refund credit',
    input: {
      source: 'sms',
      sender: 'ZOMATO',
      body: 'Refund of Rs 349 has been credited from Zomato order Z123.',
      receivedAt: '2026-06-09T10:20:00.000Z',
    },
    expected: {
      amount: 349,
      merchant: 'Zomato',
      type: 'income',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'refund',
    },
  },
  {
    id: 'sms-paytm-cashback',
    label: 'SMS cashback credit',
    input: {
      source: 'sms',
      sender: 'PAYTMB',
      body: 'Cashback of Rs 50 credited to your Paytm Wallet for merchant payment.',
      receivedAt: '2026-06-09T10:21:00.000Z',
    },
    expected: {
      amount: 50,
      merchant: 'PAYTMB',
      type: 'income',
      paymentMethod: 'wallet',
      status: 'draft',
      shouldDraft: true,
      category: 'refund',
    },
  },
  {
    id: 'sms-ambiguous-bank-debit-review',
    label: 'SMS ambiguous debit needs review',
    input: {
      source: 'sms',
      sender: 'SBIBNK',
      body: 'Your account was debited by Rs 999.00. Ref 111122223333.',
      receivedAt: '2026-06-09T10:22:00.000Z',
    },
    expected: {
      amount: 999,
      merchant: 'SBIBNK',
      type: 'expense',
      paymentMethod: 'bank',
      status: 'review',
      shouldDraft: true,
    },
  },
  {
    id: 'sms-otp-with-amount',
    label: 'SMS OTP containing amount',
    input: {
      source: 'sms',
      sender: 'AXISBK',
      body: 'OTP 123456 for transaction of Rs 10,000 at TEST SHOP is valid for 5 minutes. Do not share it.',
      receivedAt: '2026-06-09T10:23:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'otp',
    },
  },
  {
    id: 'sms-promotional-offer',
    label: 'SMS promotional cashback offer',
    input: {
      source: 'sms',
      sender: 'PHONPE',
      body: 'Get cashback up to Rs 200 on your next UPI payment. Offer valid today.',
      receivedAt: '2026-06-09T10:24:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'promotional',
    },
  },
  {
    id: 'otp-with-amount',
    label: 'OTP containing amount',
    input: {
      source: 'notification',
      sourceApp: 'Axis Bank',
      title: 'OTP',
      body: 'OTP 123456 for transaction of Rs 10,000 is valid for 5 minutes. Do not share it.',
      receivedAt: '2026-06-09T10:20:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'otp',
    },
  },
  {
    id: 'failed-upi',
    label: 'Failed UPI payment',
    input: {
      source: 'notification',
      sourceApp: 'Google Pay',
      title: 'Payment failed',
      body: 'Your UPI payment of Rs 500 to BIG BASKET failed. No money was debited.',
      receivedAt: '2026-06-09T10:25:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'failed',
    },
  },
  {
    id: 'declined-card',
    label: 'Declined card transaction',
    input: {
      source: 'notification',
      sourceApp: 'ICICI Bank',
      title: 'Transaction declined',
      body: 'Credit Card transaction of Rs 800 at NETFLIX was declined due to insufficient limit.',
      receivedAt: '2026-06-09T10:30:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'declined',
    },
  },
  {
    id: 'low-balance-alert',
    label: 'Low balance alert',
    input: {
      source: 'notification',
      sourceApp: 'SBI',
      title: 'Low balance alert',
      body: 'Your account balance is below Rs 1,500. Maintain minimum balance to avoid charges.',
      receivedAt: '2026-06-09T10:35:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'low balance',
    },
  },
  {
    id: 'statement-reminder',
    label: 'Statement reminder',
    input: {
      source: 'notification',
      sourceApp: 'HDFC Bank',
      title: 'Statement ready',
      body: 'Your credit card statement is ready. Total spends Rs 12,000, payment due by 20-Jun.',
      receivedAt: '2026-06-09T10:40:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'statement',
    },
  },
  {
    id: 'promotional-cashback',
    label: 'Promotional cashback offer',
    input: {
      source: 'notification',
      sourceApp: 'PhonePe',
      title: 'Cashback offer',
      body: 'Get cashback up to Rs 200 on your next UPI payment. Offer valid today.',
      receivedAt: '2026-06-09T10:45:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'promotional',
    },
  },
  {
    id: 'autopay-mandate',
    label: 'Autopay mandate setup',
    input: {
      source: 'notification',
      sourceApp: 'BHIM',
      title: 'Mandate created',
      body: 'UPI AutoPay mandate for Rs 999 has been created for MUSIC STREAMING. Payments will start next month.',
      receivedAt: '2026-06-09T10:50:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'mandate',
    },
  },
  {
    id: 'sms-axis-upi-mandate-revoked',
    label: 'SMS Axis UPI mandate revoked',
    input: {
      source: 'sms',
      sender: 'AXISBK',
      body: 'Your UPI mandate has been successfully revoked towards YouTube for INR 89.00 - Axis Bank',
      receivedAt: '2026-06-09T06:00:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'mandate',
    },
  },
  {
    id: 'sms-axis-upi-mandate-created',
    label: 'SMS Axis UPI ASPRESENTED mandate created',
    input: {
      source: 'sms',
      sender: 'AXISBK',
      body: 'Your UPI ASPRESENTED mandate has been successfully created towards OpenAI LLC from 05-06-26 to 02-06-36 for INR 1999.00 - Axis Bank',
      receivedAt: '2026-06-05T04:00:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'mandate',
    },
  },
  {
    id: 'login-alert',
    label: 'Login security alert',
    input: {
      source: 'notification',
      sourceApp: 'Paytm',
      title: 'Login alert',
      body: 'New login detected on your Paytm account from Android device.',
      receivedAt: '2026-06-09T10:55:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'amount',
    },
  },
  {
    id: 'reversal-before-settlement',
    label: 'Reversal before settlement',
    input: {
      source: 'notification',
      sourceApp: 'SBI Card',
      title: 'Reversal alert',
      body: 'Transaction of Rs 1,299 at AIRLINE PORTAL was reversed before settlement. No amount is payable.',
      receivedAt: '2026-06-09T11:00:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'reversed',
    },
  },
  {
    id: 'upi-collect-request',
    label: 'UPI collect request',
    input: {
      source: 'notification',
      sourceApp: 'Google Pay',
      title: 'Payment request',
      body: 'COLLECT request from STORE MART for Rs 400 is pending. Approve to pay.',
      receivedAt: '2026-06-09T11:05:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'request',
    },
  },
  {
    id: 'card-bill-due',
    label: 'Credit card bill due',
    input: {
      source: 'notification',
      sourceApp: 'ICICI Bank',
      title: 'Bill due',
      body: 'Your credit card bill of Rs 5,000 is due on 21-Jun. Pay now to avoid late fee.',
      receivedAt: '2026-06-09T11:10:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'bill due',
    },
  },
  {
    id: 'info-merchant-bigbasket',
    label: 'Bank info merchant format',
    input: {
      source: 'notification',
      sourceApp: 'HDFC Bank',
      title: 'Debit Alert',
      body: 'A/c XX123 debited by Rs 2,000.00 on 09-Jun. Info: BIG BASKET UPI Ref 444455556666.',
      receivedAt: '2026-06-09T11:15:00.000Z',
    },
    expected: {
      amount: 2000,
      merchant: 'BIG BASKET',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'shopping',
    },
  },
  {
    id: 'ambiguous-bank-debit-review',
    label: 'Ambiguous debit with amount',
    input: {
      source: 'notification',
      sourceApp: 'Bank App',
      title: 'Debit Alert',
      body: 'Your account was debited by Rs 999.00. Ref 111122223333.',
      receivedAt: '2026-06-09T11:20:00.000Z',
    },
    expected: {
      amount: 999,
      merchant: 'Bank App',
      type: 'expense',
      paymentMethod: 'bank',
      status: 'review',
      shouldDraft: true,
    },
  },
  {
    id: 'wallet-refund-review',
    label: 'Wallet refund needs review',
    input: {
      source: 'notification',
      sourceApp: 'Amazon Pay',
      title: 'Refund initiated',
      body: 'Refund of INR 250 has been initiated for your order and will be credited once processed.',
      receivedAt: '2026-06-09T11:25:00.000Z',
    },
    expected: {
      status: 'review',
      shouldDraft: true,
      amount: 250,
      type: 'income',
      paymentMethod: 'wallet',
      merchant: 'Amazon Pay',
      category: 'refund',
    },
  },
  {
    id: 'sms-hdfc-upi-akshay-rs1',
    label: 'HDFC UPI debit to person for one rupee',
    input: {
      source: 'sms',
      sender: 'AX-HDFCBK',
      body: 'A/c XX4321 debited by Rs 1.00 for UPI payment to AKSHAY PAINJANE. UPI Ref 412345678901.',
      receivedAt: '2026-06-09T12:00:00.000Z',
    },
    expected: {
      amount: 1,
      merchant: 'AKSHAY PAINJANE',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
    },
  },
  {
    id: 'sms-icici-upi-rrn',
    label: 'ICICI UPI debit with RRN',
    input: {
      source: 'sms',
      sender: 'AD-ICICIB',
      body: 'ICICI Bank Acct XX9001 debited for Rs 640.00 on 10-06-26 to APOLLO PHARMACY via UPI. RRN 512345678901.',
      receivedAt: '2026-06-10T11:00:00.000Z',
    },
    expected: {
      amount: 640,
      merchant: 'APOLLO PHARMACY',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'healthcare',
    },
  },
  {
    id: 'sms-kotak-upi-utr',
    label: 'Kotak UPI debit with UTR',
    input: {
      source: 'sms',
      sender: 'VK-KOTAKB',
      body: 'Sent Rs. 875.00 to BIG BASKET from Kotak A/c XX4444 via UPI. UTR 612345678901.',
      receivedAt: '2026-06-10T11:05:00.000Z',
    },
    expected: {
      amount: 875,
      merchant: 'BIG BASKET',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'shopping',
    },
  },
  {
    id: 'sms-adib-card-approved-aed',
    label: 'ADIB card approved message in AED',
    input: {
      source: 'sms',
      sender: 'ADIB',
      body: 'Trx. of AED45.00 on your card ending *510 at GLOBAL VILLAGE D, UAE is Approved. Avl. card bal is 1955.00. Trx Date: 28/01/23 18:54',
      receivedAt: '2023-01-28T18:54:00.000Z',
    },
    expected: {
      amount: 45,
      merchant: 'GLOBAL VILLAGE D',
      type: 'expense',
      paymentMethod: 'card',
      status: 'draft',
      shouldDraft: true,
      category: 'entertainment',
    },
  },
  {
    id: 'sms-adib-account-pos-aed',
    label: 'ADIB account POS transaction in AED',
    input: {
      source: 'sms',
      sender: 'ADIB',
      body: 'Trx. of AED 48.00 on your a/c ****6111 at NAJD PALACE RESTAURANT ABU DHABI AE. Avl Bal is AED 8593.24',
      receivedAt: '2017-09-08T10:30:21.000Z',
    },
    expected: {
      amount: 48,
      merchant: 'NAJD PALACE RESTAURANT ABU DHABI AE',
      type: 'expense',
      paymentMethod: 'bank',
      status: 'draft',
      shouldDraft: true,
      category: 'food',
    },
  },
  {
    id: 'sms-adib-account-credit-review',
    label: 'ADIB account credit in AED',
    input: {
      source: 'sms',
      sender: 'ADIB',
      body: 'Dear Customer, AED 3000.00 was credited to your account ****2486. Your available account balance is AED 3000.00',
      receivedAt: '2019-05-30T05:58:43.000Z',
    },
    expected: {
      amount: 3000,
      merchant: 'ADIB',
      type: 'income',
      paymentMethod: 'bank',
      status: 'review',
      shouldDraft: true,
    },
  },
  {
    id: 'sms-adib-card-payment-credited-ignore',
    label: 'ADIB card payment credit confirmation',
    input: {
      source: 'sms',
      sender: 'ADIB',
      body: 'Dear Customer, your payment of AED 100.00 on 7/29/2020 for card ending with **0121 has been credited. Thank you.',
      receivedAt: '2020-07-29T19:31:00.000Z',
    },
    expected: {
      status: 'ignore',
      shouldDraft: false,
      ignoreReasonIncludes: 'card payment',
    },
  },
  {
    id: 'notification-phonepe-upi-person',
    label: 'PhonePe UPI notification without UPI word',
    input: {
      source: 'notification',
      sourceApp: 'PhonePe',
      title: 'Payment successful',
      body: 'Paid Rs 75 to PERSON A. Transaction ID T250610123456.',
      receivedAt: '2026-06-10T11:10:00.000Z',
    },
    expected: {
      amount: 75,
      merchant: 'PERSON A',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
    },
  },
  {
    id: 'notification-gpay-upi-store',
    label: 'Google Pay UPI notification without UPI word',
    input: {
      source: 'notification',
      sourceApp: 'Google Pay',
      title: 'Payment successful',
      body: 'You paid Rs 149 to NETFLIX INDIA. Transaction ID G250610123456.',
      receivedAt: '2026-06-10T11:15:00.000Z',
    },
    expected: {
      amount: 149,
      merchant: 'NETFLIX INDIA',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'entertainment',
    },
  },
  {
    id: 'duplicate-hdfc-upi-cafe',
    label: 'Duplicate HDFC UPI debit update',
    input: {
      source: 'notification',
      sourceApp: 'HDFC Bank',
      title: 'HDFC Bank',
      body: 'Rs 789.50 debited from account for UPI payment to PHASE ONE CAFE. UPI Ref 412345678901.',
      receivedAt: '2026-06-09T09:02:00.000Z',
    },
    expected: {
      amount: 789.5,
      merchant: 'PHASE ONE CAFE',
      type: 'expense',
      paymentMethod: 'upi',
      status: 'draft',
      shouldDraft: true,
      category: 'food',
    },
  },
];
