import { SITE } from './site';
import { MANUAL_SMS_DISCLOSURE, SMS_DISCLOSURE } from './smsConsent';

export const LEGAL_UPDATED = 'September 30, 2026';
export const PRIVACY_SECTIONS = [
  { title: 'Who operates MoneyKai', body: `MoneyKai provides personal finance tracking and shared expenses. For privacy questions or requests contact ${SITE.supportEmail}. This policy covers the MoneyKai app and website.` },
  { title: 'Account and financial records', body: 'MoneyKai processes account identity, preferences and the financial records you create or confirm, including amounts, dates, categories, budgets and shared expenses. Non-SMS signed-in records may sync with Firebase and MoneyKai services to provide the features you request. SMS-derived records remain on-device and are excluded from cloud sync and cloud backups. Shared records are visible to the people you intentionally share them with.' },
  { title: 'Messages you paste', body: MANUAL_SMS_DISCLOSURE },
  { title: 'Optional SMS inbox access', body: `Default public builds do not request inbox access. In a distribution configured for SMS capture, MoneyKai presents a separate disclosure and asks for your affirmative consent before Android SMS permission. ${SMS_DISCLOSURE} Permission is not a condition of using manual tracking.` },
  { title: 'Purchase tools', body: 'Before You Buy calculates budget impact from confirmed spending and commitments you enter; scenario inputs are not saved. Price Memory stores the item prices, quantities, shops, dates and optional transaction links you enter on this phone, separated by account. It is not currently cloud-synced or included in MoneyKai backups. Neither tool infers individual product prices from a bank-payment total.' },
  { title: 'Contacts and storage', body: 'Contacts permission is optional and requested when you use the People picker; only selected people are attached to records. You can enter names without contacts access. SMS parsing and purchase tools do not require contacts or broad storage permissions.' },
  { title: 'Security and service providers', body: 'Data sent to MoneyKai services uses HTTPS. This is encryption in transit, not end-to-end encryption: authorized services can process synced records. On Android, transaction records, capture drafts, app notifications and Price Memory use authenticated encryption with a device Keystore key. Other preferences may use ordinary private app storage. Exported encrypted backup files are a separate feature. Do not enter passwords, PINs, OTPs or full card credentials in record fields. Financial data is not sold or used for advertising.' },
  { title: 'Retention and control', body: `Discard pasted-message previews without saving. Redacted capture drafts remain on the device until cleared, app data is erased or the app is uninstalled; confirmed records remain in your account until deleted. Price Memory entries can be deleted individually. Turning capture off stops future reading but does not revoke the OS permission or delete existing records; revoke access in Android Settings and clear drafts separately. Signing out clears capture consent and drafts; local Price Memory remains separated by account. Delete your account in Profile → Security & data → Delete account, or request deletion at ${SITE.url}/account-deletion. The in-app confirmed deletion also removes this account’s Price Memory on this device. Other devices and separately exported files must be cleared separately.` },
  { title: 'Website and diagnostics', body: 'Necessary website storage may support sign-in, preferences and security. The Android app does not use web cookies. The default public build disables remote diagnostic uploads; raw SMS is not included in MoneyKai backup or diagnostic payloads. Optional features must describe any additional data use before activation.' },
];
export const TERMS_SECTIONS = [
  { title: 'Using MoneyKai', body: 'By using MoneyKai you agree to these terms and the privacy policy. If you do not agree, do not use the service. Permission consent is separate from accepting terms, and optional access may be declined without losing manual tracking.' },
  { title: 'SMS parsing and your control', body: 'Use SMS parsing only for messages on your own device that you are entitled to process. It suggests details for completed financial transactions and may misread or miss bank formats. Review the amount, date, direction and category before confirming. MoneyKai does not send SMS, make payments, verify your bank credentials or use SMS permissions to authenticate you. Automatic access is available only in specifically configured distributions and is subject to applicable platform permission requirements; these terms do not imply Google approval.' },
  { title: 'Data and sync', body: 'Only confirmed transaction details enter your financial ledger. SMS-derived records stay encrypted on-device and are excluded from cloud sync and cloud backups; raw SMS and security credentials are not uploaded. Other signed-in records may sync over HTTPS, which is not end-to-end encryption. Keep your device and account secure, and do not place credentials in transaction descriptions. You control sharing and exported files.' },
  { title: 'Before You Buy and Price Memory', body: 'Budget-impact estimates are scenarios, not available bank balances, guarantees of affordability, forecasts or professional advice. They depend on your monthly budget, confirmed expenses and commitments you enter. Price comparisons use your recorded prices and normalized units, not live market prices; compare the same product and variant. Local price history is not presently synced or backed up, and clearing app data or uninstalling may remove it.' },
  { title: 'Accuracy and availability', body: 'You remain responsible for reviewing entered and imported records and keeping appropriate backups. Features may be unavailable because of connectivity, permissions, maintenance or bugs. MoneyKai does not replace professional financial, legal, tax or investment advice. Report mistakes rather than relying on an unverified calculation.' },
  { title: 'Deletion and support', body: `You may delete records and request account deletion in the app or at ${SITE.url}/account-deletion. These terms do not limit statutory rights. Contact ${SITE.supportEmail} for questions about the service or these terms.` },
];
