export const SITE = {
  name: 'MoneyKai',
  url: 'https://moneykai.app',
  supportEmail: 'support@moneykai.app',
  title: 'MoneyKai | Local-first budget and expense tracker',
  description:
    'MoneyKai is a local-first personal finance app for recording expenses, budgets, shared spending, savings, and encrypted backup files on Android.',
};

export const PUBLIC_ROUTES = [
  '',
  '/about',
  '/contact',
  '/faq',
  '/features',
  '/features/expense-tracking',
  '/features/budgeting',
  '/features/groups',
  '/features/savings',
  '/features/analytics',
  '/features/backup-restore',
  '/how-it-works',
  '/pricing',
  '/news',
  '/trust',
  '/security',
  '/financial-first-aid',
  '/privacy-policy',
  '/terms',
  '/learn',
  '/learn/budgeting',
  '/learn/saving-money',
  '/learn/expense-tracking',
  '/learn/personal-finance',
  '/learn/how-to-track-daily-expenses',
  '/learn/monthly-budget-planner',
  '/learn/50-30-20-budget-rule',
  '/learn/how-students-can-save-money',
  '/learn/how-to-stop-overspending',
  '/learn/emergency-fund-guide',
  '/learn/budget-tracker-vs-expense-tracker',
  '/learn/personal-finance-for-beginners',
  '/learn/how-to-manage-shared-expenses',
];
