export const SMS_CONSENT_VERSION = '2026-09-30-v2';
export const MANUAL_SMS_CONSENT_VERSION = '2026-09-30-v1';
export const SMS_AUTO_ADD_CONSENT_VERSION = '2026-09-30-auto-add-v1';
export const SMS_AUTO_ADD_DISCLOSURE = 'Automatically save recognized SMS transactions from bank accounts you approve. MoneyKai only auto-adds completed INR payments with a clear amount, direction, date, transaction reference and reliable category evidence. Unknown, suspicious, ambiguous or incomplete messages stay in Review drafts. Categories can still be wrong: this is not a zero-error guarantee. Check your records regularly, especially before using totals for tax or compliance. You can edit or delete auto-added records in Transactions and turn auto-add off here. Your confirmations teach exact counterparty categories on this phone only; automatic guesses never train themselves. SMS-derived records and learned rules stay encrypted on this device and are not uploaded.';
export const hasCurrentSmsAutoAddConsent = (settings: { autoAddRecognizedSms?: boolean; smsAutoAddConsentVersion?: string; smsAutoAddConsentUserId?: string; smsAutoAddConsentAcceptedAt?: string }, owner?: string | null) => Boolean(owner && settings.autoAddRecognizedSms && settings.smsAutoAddConsentUserId === owner && settings.smsAutoAddConsentVersion === SMS_AUTO_ADD_CONSENT_VERSION && settings.smsAutoAddConsentAcceptedAt && Number.isFinite(Date.parse(settings.smsAutoAddConsentAcceptedAt)));
export const hasCurrentManualSmsConsent = (settings: { manualSmsConsentVersion?: string; manualSmsConsentUserId?: string; manualSmsConsentAcceptedAt?: string }, userId?: string | null) => Boolean(userId && settings.manualSmsConsentUserId === userId && settings.manualSmsConsentVersion === MANUAL_SMS_CONSENT_VERSION && settings.manualSmsConsentAcceptedAt && Number.isFinite(Date.parse(settings.manualSmsConsentAcceptedAt)));
export const hasCurrentSmsConsent = (settings: { smsConsentVersion?: string; smsConsentUserId?: string; smsResearchExplainerAcceptedAt?: string }, userId?: string | null) => Boolean(userId && settings.smsConsentUserId === userId && settings.smsConsentVersion === SMS_CONSENT_VERSION && settings.smsResearchExplainerAcceptedAt && Number.isFinite(Date.parse(settings.smsResearchExplainerAcceptedAt)));
export const SMS_DISCLOSURE = 'MoneyKai reads SMS on this phone to identify completed bank and payment transactions. After you agree and grant Android SMS permission, Turn On immediately checks your selected recent history for bank accounts and transactions. It then checks new messages in the background, including while the app is closed, at your selected interval. Android may delay checks to save battery. Start Parsing repeats a check of the recent range you choose. You approve bank accounts before their messages are parsed. By default, review drafts before saving transactions. If you separately enable auto-add and accept its disclosure, reliably recognized completed transactions are saved automatically; uncertain transactions still need review. Messages are filtered offline; unrelated messages, OTPs, PINs, passwords, offers and failed payments are ignored. Redacted drafts, masked account hints and SMS-derived transactions stay encrypted on this phone with a device Keystore key. Background results are queued encrypted and processed when the app opens. SMS and SMS-derived records are not uploaded or included in cloud backups. You can decline, turn automatic reading off, or revoke SMS permission in Android Settings. Turning off stops scheduled checks but does not delete existing records or revoke Android permission. Manual entry remains available.';

export const MANUAL_SMS_DISCLOSURE = 'MoneyKai processes only the message you paste, offline on this phone, to suggest transaction details. Unrelated messages and security codes are ignored. The pasted text is discarded after parsing; no SMS inbox permission is requested. Only the details you review and confirm are saved, encrypted on this phone with a device Keystore key. SMS-derived transactions, raw SMS, OTPs, PINs and passwords are not uploaded or included in cloud backups. Protect your device; uninstalling or clearing its storage may permanently remove these local records.';
